{ pkgs ? import <nixpkgs> {} }:
{
  buildInputs = with pkgs; [
    linuxHeaders
    man-pages
    iana-etc
    glibc
    zlib
    bzip2
    xz
    lz4
    zstd
    file
    readline
    pcre2
    gnum4
    gavin-bc
    flex
    tcl
    expect
    dejagnu
    pkg-config
    binutils
    gmp
    mpfr
    libmpc
    attr
    acl
    libcap
    libxcrypt
    shadow
    gcc
    ncurses
    gnused
    psmisc
    gettext
    bison
    gnugrep
    bash
    libtool
    gdbm
    gperf
    expat
    inetutils
    less
    perl
    perl5Packages.XMLParser
    intltool
    autoconf
    automake
    openssl_3_6
    elfutils
    libffi
    sqlite
    python314
    python314Packages.flit-core
    python314Packages.packaging
    python314Packages.wheel
    python314Packages.setuptools
    python313Packages.flit-core
    python313Packages.packaging
    python313Packages.wheel
    python313Packages.setuptools
    ninja
    python314Packages.meson
    python313Packages.meson
    kmod
    coreutils
    diffutils
    gawk
    findutils
    groff
    grub2
    gzip
    iproute2
    kbd
    libpipeline
    gnumake
    gnupatch
    gnutar
    texinfo
    vim
    python314Packages.markupsafe
    python314Packages.jinja2
    python313Packages.markupsafe
    python313Packages.jinja2
    systemd
    dbus
    man
    procps
    util-linux
    e2fsprogs
  ];
}
